# Generated by Django 5.0.7 on 2024-07-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_manager', '0002_resume_education_resume_email_resume_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
