# Generated by Django 5.0.7 on 2024-07-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_manager', '0003_alter_resume_education_alter_resume_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
    ]
